# Generated by Django 3.1 on 2021-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('subscriber_first_name', models.CharField(max_length=100)),
                ('subscriber_last_name', models.CharField(max_length=100)),
                ('subscriber_email', models.EmailField(max_length=100)),
            ],
            options={
                'ordering': ['-date_subscribed'],
            },
        ),
    ]
