# Generated by Django 3.1 on 2021-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enter', models.DateTimeField(auto_now_add=True)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_phone_no', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=100)),
                ('status', models.CharField(choices=[('CLOSED', 'Closed'), ('INTERESTED', 'Interested'), ('ONGOING', 'Ongoing')], max_length=200)),
            ],
            options={
                'ordering': ['-date_enter'],
            },
        ),
    ]
