# Generated by Django 3.1 on 2021-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer_phone_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('INTERESTED', 'Interested'), ('ONGOING', 'Ongoing')], default='ONGOING', max_length=200),
        ),
    ]
